#!/usr/bin/python3
import requests
import sys
import getopt
import sys
import getopt
import re
from rich import print
from rich.padding import Padding
from rich.panel import Panel
from rich import print
from rich.layout import Layout
from rich.align import Align
from rich.console import Console
from rich.text import Text

def escape_ansi(line):
    ansi_escape =re.compile(r'(\x9B|\x1B\[)[0-?]*[ -\/]*[@-~]')
    return ansi_escape.sub('', line)

def command_name():
    command_name = None

    argv = sys.argv[1:]

    try:
        opts, args = getopt.getopt(argv, "c:", "command_name =")

    except:
        print("Error")

    for opt, arg in opts:
      opt = opt.strip()
      if opt in ['-c', '--command_name']:
          url = f"http://cheat.sh/{arg}"
          payload = "ls"
          headers = {
          'Content-Type': 'text/plain'
          }
          console = Console()
          layout = Layout()

          response = requests.request("GET", url, headers=headers, data=payload)
          tldr_text = escape_ansi(response.text).split("tldr:")[1]
          tldr_text_line_formatting = tldr_text.split("\n\n#")
          empty = ""
          formatted_text = Text(empty)
          for line in tldr_text_line_formatting:
            if line[0] == " ":
                line = line.strip() + "\n\n"
                line = Text(line)
                line.stylize("bold light_steel_blue")
                formatted_text.append(line)
            else:
                line = line.strip() + "\n\n\n"
                formatted_text.append(line)

          command_title = tldr_text.split("\n")[0]
          command_title_text = Text(command_title.strip())
          command_title_text.stylize("bold white u")
          command_title = Align.center(command_title_text, vertical="middle")
          formatted_text = Align.center(formatted_text, vertical="middle")
          layout.split_column(
            Layout(name="upper"),
            Layout(name="lower")
          )
          layout["upper"].size = 11
          layout["upper"].update(Panel(command_title))
          layout["lower"].update(Panel(formatted_text))
          layout = Padding(layout, (4,0,0,0))
          print(layout)

command_name()
